In [5]:
import pandas as pd 
import numpy as np 
import random



Quantiles:


Quantiles divide your dataset into equal parts, and the term "quantile" is a general term that refers to any division of your data. Percentiles are a type of quantile where the division is based on percentages.


Also, Quartiles are a specific type of quantile that divide your dataset into four equal parts.

A Percentile is a value below which a certain percentage of observations lie.

If you have the GRE scores of 10 students and you calculate percentiles, quantiles, and quartiles, the results will provide you with valuable insights into the distribution of the scores and how each student's score compares to others. 

Percentiles:
Percentiles provide you with information about the relative position of a student's score within the dataset. For example, if a student's score is at the 75th percentile, it means their score is higher than 75% of the scores in the dataset. 


In other words, a Percentile is a value below which a certain percentage of observations lie.


As already discussed, percentiles are a type of quantile where the division is based on percentages.

Cossider this dataset: 

sorted_scores = [65, 70, 72, 75, 78, 80, 82, 85, 88, 90, 92, 95, 98, 100, 102, 105, 108, 110, 112, 115,120]

In this example, if you want to find the score at the 25th percentile, it means 25% of the data falls below that score. Similarly, the score at the 50th percentile is the median, and the score at the 75th percentile means 75% of the data falls below that score.




formula : 


calculate percentile = (Position of value in sorted list/total no of observations) * 100




Step-by-Step Calculation:

Q1 (First Quartile):



The position for Q1 is (25 / 100) * (21 + 1) = 5.25, which rounds up to position 6.
The sixth value in the sorted dataset is 80, which is the value of Q1.
Q2 (Second Quartile, Median):



For an odd number of data points, the median is simply the middle value.
In this case, the middle value is the eleventh value, which is 92.
Q3 (Third Quartile):

The position for Q3 is (75 / 100) * (21 + 1) = 15.75, which rounds up to position 16.
The sixteenth value in the sorted dataset is 105, which is the value of Q3.
So, for the dataset [65, 70, 72, 75, 78, 80, 82, 85, 88, 90, 92, 95, 98, 100, 102, 105, 108, 110, 112, 115, 120], the quartiles are:



Q1: 80
Q2 (Median): 92
Q3: 105
These quartile values help you understand the spread and distribution of the data points in the dataset.

In [70]:
import numpy as np

# Step 1: Generate Fake GRE Scores for 10 Students
# np.random.seed(42)  # For reproducibility
# gre_scores = np.random.randint(300, 340, size=10)  # Generate scores between 300 and 340

# Step 2: Sort the Scores
sorted_scores = [65, 70, 72, 75, 78, 80, 82, 85, 88, 90, 92, 95, 98, 100, 102, 105, 108, 110, 112, 115,120]

print(sorted_scores)

# Step 3: Calculate Percentiles
percentiles = [10, 25, 50, 75, 90]
percentile_values = np.percentile(sorted_scores, percentiles)

# Step 4: Calculate Quantiles (Quartiles)
q1 = np.percentile(sorted_scores, 25)
q2 = np.percentile(sorted_scores, 50)
q3 = np.percentile(sorted_scores, 75)

# Step 5: Print Results

print("Sorted GRE Scores:", sorted_scores)
print('\n')
print("Percentiles:", list(zip(percentiles, percentile_values)))
print('\n')
print("Q1 (First Quartile):", q1)
print("Q2 (Median):", q2)
print("Q3 (Third Quartile):", q3)


[65, 70, 72, 75, 78, 80, 82, 85, 88, 90, 92, 95, 98, 100, 102, 105, 108, 110, 112, 115, 120]
Sorted GRE Scores: [65, 70, 72, 75, 78, 80, 82, 85, 88, 90, 92, 95, 98, 100, 102, 105, 108, 110, 112, 115, 120]


Percentiles: [(10, 72.0), (25, 80.0), (50, 92.0), (75, 105.0), (90, 112.0)]


Q1 (First Quartile): 80.0
Q2 (Median): 92.0
Q3 (Third Quartile): 105.0


The percentiles represent the values that divide your dataset into specific percentages. For example:
At the 10th percentile, 10% of the students mark falls below or is equal to the value of 72.0.
At the 25th percentile, 25% of the students mark falls  below or is equal to the value of 80.0.
At the 50th percentile (median), 50% of the students mark falls below or is equal to the value of 92.0.
At the 75th percentile, 75% of the students mark falls below or is equal to the value of 105.0.
At the 90th percentile, 90% of the students mark falls below or is equal to the value of 112.0.

In [ ]:
Quartiles:

The quartiles are specific percentiles that divide your dataset into four equal parts.
Q1 (First Quartile): 25% of the data falls below or is equal to the value of 80.0.
Q2 (Second Quartile, Median): 50% of the data falls below or is equal to the value of 92.0.
Q3 (Third Quartile): 75% of the data falls below or is equal to the value of 105.0.

In summary, these values provide insights into the distribution of your data. For instance, you can say that 50% of the scores are below 92.0, and 25% of the scores are below 80.0. The quartiles help you understand how the data is spread across different ranges. Percentiles and quartiles are often used in statistics to describe the central tendency and variability of a dataset